name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [0.33.0, latest]

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - name: Download source
      uses: actions/checkout@v2
    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Format check
      run: crystal tool format --check
